config/routes.rb
Rails.application.routes.draw do
  
  resources :members
  resources :families

  root to: "home#index"
  get 'home/index', to: 'home#index'
  
  # go to this action/page after the devise login
  get 'members', to: 'members#index', as: :user_root

  devise_for :users, :skip => [:registrations]
    
  devise_scope :user do 
     get 'login', controller: 'devise/sessions', action: 'create'
     get 'logout', controller: 'devise/sessions', action: 'destroy'
  end

  namespace :api do
    namespace :v1 do
        match '/summary', controller: 'summary', action: :show, via: [:get, :options]

        match '/events', controller: 'events', action: :index, via: [:get, :options]
        match '/events/:id', controller: 'events', action: :show, via: [:get, :options]

        match '/members', controller: 'members', action: :index,  via: [:get, :options]
        match '/members/:id', controller: 'members', action: :show, via: [:get, :options]
    end
  end
  
end

app/models/family.rb
class Family < ApplicationRecord
  
  # belongs_to :wife, class_name: 'Member', optional: true
  # belongs_to :husband, class_name: 'Member', optional: true
  
  has_many :children, class_name: 'Member', foreign_key: "family_id"
  
  has_many :memberships
  has_many :members, through: :memberships
  
  def to_s
    "<Family##{id} #{key} #{name}>"
  end
  
  def display_name
    name ? name : built_name
  end
  
  def built_name
    return "error1" unless members
    return "error2" unless members[0]
    name = members[0] ? members[0].first_name : ''
    name += ' & ' if name.length > 0 && members[1]
    name += members[1].first_name if members[1]
    return name
  end
  
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  
  before_action :set_family, only: [:show, :edit, :update, :destroy]
  
  before_action :authenticate_user! #, except: [:home, :about, :contact]

  # GET /families
  # GET /families.json
  def index
    @families = Family.all
  end

  # GET /families/1
  # GET /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families
  # POST /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: 'Family was successfully created.' }
        format.json { render :show, status: :created, location: @family }
      else
        format.html { render :new }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1
  # PATCH/PUT /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to @family, notice: 'Family was successfully updated.' }
        format.json { render :show, status: :ok, location: @family }
      else
        format.html { render :edit }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.json
  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_url, notice: 'Family was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_params
      params.require(:family).permit(:name, :key, :husb_key, :wife_key)
    end
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_form.html.erb
<%= form_for(family) do |f| %>
  <% if family.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(family.errors.count, "error") %> prohibited this family from being saved:</h2>

      <ul>
      <% family.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :key %>
    <%= f.text_field :key %>
  </div>

  <div class="field">
    <%= f.label :husb_key %>
    <%= f.text_field :husb_key %>
  </div>

  <div class="field">
    <%= f.label :wife_key %>
    <%= f.text_field :wife_key %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/families/edit.html.erb
<h1>Editing Family</h1>

<%= render 'form', family: @family %>

<%= link_to 'Show', @family %> |
<%= link_to 'Back', families_path %>

app/views/families/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Families</h1>

<table class="table table-striped" >
  <thead>
    <tr>
		<th>ID</th>
      	<th>Name</th>
      	<th>Spouse 1</th>
      	<th>Spouse 2</th>
      	<th>Children</th>
    </tr>
  </thead>

  <tbody>
    <% @families.each do |family| %>
		
      <tr>
		<td><%= family.id %></td>
		<td>
			<%= image_tag("family.png", size: "20x20") %>
			<%= link_to family.display_name, family %>
		</td>
        <td>
			<% if family.members[0] %>
			<%= image_tag("member.png", size: "20x20") %>
			<%= link_to family.members[0].try(:full_name), family.members[0] %>
			<% end %>
		</td>
        <td>
			<% if family.members[1] %>
			<%= image_tag("member.png", size: "20x20") %>
			<%= link_to family.members[1].try(:full_name), family.members[1] %>
			<% end %>
		</td>
        <td><%= family.children.count > 0 ? family.children.count : '' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Family', new_family_path %> -->

app/views/families/new.html.erb
<h1>New Family</h1>

<%= render 'form', family: @family %>

<%= link_to 'Back', families_path %>

app/views/families/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @family.display_name %></h1>

  <% @family.members.all.each do |member| %>
  	<br><%= link_to member.display_name, member %>
  <% end %>

  <br>
  <br><strong>Parent(s)</strong>
  <% @family.members.all.each do |spouse| %>
	<% if spouse.family %>
    	<br><%= link_to spouse.family.display_name, spouse.family %> << <%= spouse.first_name %>
	<% end %>
  <% end %>
  
  
  <% if @family.children %>
  <br>
  <br><strong>Children</strong>
  <% @family.children.all.each do |child| %>
    <br>>> <%= link_to child.display_name, child %> <%= child.display_dates %>
	<% if child.families %> 
		<% child.families.each do |f| %>
			<% text = "#{f.display_name} (#{f.children.count})"%>
			&nbsp;&nbsp;&nbsp;<%= link_to text, f %>
		<% end %>
	<% end %>
	
  <% end %>
  <% end %>
  
<br><br><br>
<%= link_to 'Edit', edit_family_path(@family) %> |
<%= link_to 'List', families_path %>