config/routes.rb
Rails.application.routes.draw do
  
  resources :members
  resources :families

  root to: "home#index"
  get 'home/index', to: 'home#index'
  
  # go to this action/page after the devise login
  get 'members', to: 'members#index', as: :user_root

  devise_for :users, :skip => [:registrations]
    
  devise_scope :user do 
     get 'login', controller: 'devise/sessions', action: 'create'
     get 'logout', controller: 'devise/sessions', action: 'destroy'
  end

  namespace :api do
    namespace :v1 do
        match '/summary', controller: 'summary', action: :show, via: [:get, :options]

        match '/events', controller: 'events', action: :index, via: [:get, :options]
        match '/events/:id', controller: 'events', action: :show, via: [:get, :options]

        match '/members', controller: 'members', action: :index,  via: [:get, :options]
        match '/members/:id', controller: 'members', action: :show, via: [:get, :options]
    end
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title class="red">Kazoku Rails <%= Rails.env == 'development' ? '(Local)' : '(Heroku)' %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  
	  <nav class="navbar navbar-default lichen">
	    <div class="container-fluid">
	      <!-- Brand and toggle get grouped for better mobile display -->
	      <div class="navbar-header">
	        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	          <span class="sr-only">Toggle navigation</span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	        </button>
		  	  <% if current_user %>
				<%= link_to 'Kazuko', families_path, class: "navbar-brand lichen-text"  %>
			 <% else %>
				<%= link_to 'Kazuko', root_path, class: "navbar-brand lichen-text"  %>	
			  <% end %>		
	      </div>

	      <!-- Collect the nav links, forms, and other content for toggling -->
	      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			  
	        <ul class="nav navbar-nav">
				
				<% if controller_name == 'families' %>
					<% fam_class = 'active' %>
					<% mem_class = 'lichen-text' %>
				<% elsif controller_name == 'members' %>
					<% mem_class = 'active' %>				
					<% fam_class = 'lichen-text' %>				
				<% end %>
				
		  	  <% if current_user %>
	          	<li class="<%= fam_class %>">
					<%= link_to image_tag("family.png", size: "30x30") + "Families", families_path, class: fam_class %></a>
				</li>
	            <li class="<%= mem_class %>"><%= link_to 'Members', members_path, class: mem_class %></li>
			  <% end %>
	        </ul>
			
		  	<% if current_user %>				
				<%= form_tag(members_path, :method => "get", id: "search-form", class: "navbar-form navbar-left") do %>
				    <%= text_field_tag :search, params[:search], placeholder: "Search People", class: "form-control"%>
				    <%= submit_tag "Search", :name => nil, class: "btn btn-default" %>
				<% end %>
				
			<% end %>
			
	        <ul class="nav navbar-nav navbar-right">		
			  	<% if current_user %>
			  		<li><%= link_to current_user.email, "#", class: 'lichen-text' %></li>
			  		<li><%= link_to 'Logout', logout_path, class: 'lichen-text' %></li>
			  	<% else %>
			  		<li><%= link_to 'Sign In', new_user_session_path %></li>
			  	<% end %>				  
	        </ul>
			
	      </div><!-- /.navbar-collapse -->
	    </div><!-- /.container-fluid -->
	  </nav>
	
	<!-- <%= image_tag "lichen.jpg", height: 40, width: 1200, class: "lichen" %> -->
	  
  	<% flash.each do |name, msg| %>
  		<div class="alert alert-warning">
  			<button type="button" class="close" data-dismiss="alert">&times;</button>
  			<%= msg %>
  		</div>
  	<% end %>
	   
    <%= yield %>
	
  </body>
  
</html>