config/routes.rb
Rails.application.routes.draw do
  
  resources :members
  resources :families

  root to: "home#index"
  get 'home/index', to: 'home#index'
  
  # go to this action/page after the devise login
  get 'members', to: 'members#index', as: :user_root

  devise_for :users, :skip => [:registrations]
    
  devise_scope :user do 
     get 'login', controller: 'devise/sessions', action: 'create'
     get 'logout', controller: 'devise/sessions', action: 'destroy'
  end

  namespace :api do
    namespace :v1 do
        match '/summary', controller: 'summary', action: :show, via: [:get, :options]

        match '/events', controller: 'events', action: :index, via: [:get, :options]
        match '/events/:id', controller: 'events', action: :show, via: [:get, :options]

        match '/members', controller: 'members', action: :index,  via: [:get, :options]
        match '/members/:id', controller: 'members', action: :show, via: [:get, :options]
    end
  end
  
end

app/models/member.rb
class Member < ApplicationRecord

	# a member is a child of only one family
  belongs_to :family, optional: true
  
  # but, may be a member of several marraiges
  has_many :memberships
  has_many :families, through: :memberships

  # events like birth, death, marriage
  has_many :events

	def to_s
    "<Member##{id} #{key} #{last_name}, #{first_name}>"
  end

  def self.search(search)
    where("search_text LIKE ?", "%#{search}%") 
  end

	def self.build_search_text(params)
  	search_text = ''
  	search_text += params[:first_name].downcase + ' ' if params[:first_name]
  	search_text += params[:last_name].downcase  + ' ' if params[:last_name]
  	search_text += params[:birth_year].to_s + ' ' if params[:birth_year]
  	search_text += params[:death_year].to_s + ' ' if params[:death_year]
  	return search_text
  end

  def display_name
    "#{last_name}, #{first_name}"
  end

  def birth
    # there is only one birth!
    self.events.births.first
  end

  def death
    # there is only one death!
    self.events.deaths.first
  end
  
  def full_name
    "#{first_name} #{last_name}"
  end

  def birth_year
    return 0 if birth.nil?
    return 0 if birth.year.nil?
    birth.year
  end

  def birth_string
    return '?' unless birth

    return "#{birth.month}-#{birth.day}-#{birth.year}"

    #return '?' unless birth.year > 0
    #return birth.year.to_s
  end

  def parents
    family.try :members
  end

  def siblings
    sibs = []
    kids = family ? family.children : []
    kids.each do |kid|
      sibs << kid unless kid.id == self.id
    end
    sibs.sort! { |x,y| x.birth_year <=> y.birth_year }
    return sibs
  end

  def spouses
    set = []
    families.each do |f|
      f.members.each do |m|
        set << m unless m.id == self.id
      end
    end
    return set
  end

  def children
    kids = []
    families.each do |f|
      kids.push(*f.children)
    end
    return kids
  end

  def display_range
    birth_string = self.birth.nil? ? " ? " : "#{self.birth.year}" 
    death_string = self.death.nil? ? "" : " - #{self.death.year}" 
    "(#{birth_string}#{death_string})"
  end

  def display_dates
    return "(#{self.birth_string})" unless death && death.year > 0
    return "(#{self.birth_string} - #{death.year})"
  end

  def rawtexts
    rawtext.split("\r\n")
  end

end

app/controllers/api/v1/members_controller.rb
module Api
module V1
class MembersController < ApiController

  # GET api/v1/members/1.json
  def show
  	@member = Member.find(params[:id])
  end

  # GET api/v1/members.json
  def index
    puts "*** MembersController: params=#{params.inspect}"

    # support the ability to limit the members returned
    # based on a search string criteria
    if params[:search] && params[:search].length > 0
      @members = Member.search(params[:search]).order(:id)
    else
      @members = Member.all.order(:id)
    end

    # support the ability to return pages of members
    # where each "page" is of a fixed size
    if params[:page] && params[:page].length > 0
      page = params[:page].to_i
      page = 1 if page < 1
      page = page - 1 # zero based paging
      page_size = 20  # the default page size
      page_size = params[:size].to_i if params[:size]
      start = page * page_size
      finish = start + page_size - 1
      puts "*** page #{page} is #{start} to #{finish}"
      @members = @members[start..finish]
    end

    # support the ability to return a range of members
    # from start (zero based) for a number of records (count)
    if params[:start] && params[:count]
      start = params[:start].to_i
      count = params[:count].to_i
      puts "--- Processing range: #{start} to #{start+count-1}"
      @members = @members[start..start+count-1]
    end

  end

end
end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  
  before_action :authenticate_user! #, except: [:home, :about, :contact]
  
  # GET /members
  # GET /members.json
  def index
    puts "*** MembersController: index search=#{params[:search]}"
    if params[:search] && params[:search].length > 0
      @members = Member.search(params[:search])
    else
      @members = Member.all
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, 
        :email, :gender,
        :birth_day, :birth_month, :birth_year, :birth_place,
        :death_day, :death_month, :death_year, :death_place, 
        :buried_place
      )
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(member) do |f| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :middle_name %>
    <%= f.text_field :middle_name %>
  </div>

  <div class="field">
    <%= f.label :common_name %>
    <%= f.text_field :common_name %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>

  <div class="field">
    <%= f.label :key %>
    <%= f.text_field :key %>
  </div>

  <div class="field">
    <%= f.label :famc_key %>
    <%= f.text_field :famc_key %>
  </div>

  <div class="field">
    <%= f.label :fams_keys %>
    <%= f.text_field :fams_keys %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name&nbsp;&nbsp;&nbsp;</th>
      <th>Born&nbsp;&nbsp;&nbsp;</th>
      <th>Gender&nbsp;&nbsp;&nbsp;</th>
      <th>Key&nbsp;&nbsp;&nbsp;</th>
      <th>FAMC&nbsp;&nbsp;&nbsp;</th>
      <th>FAMS&nbsp;&nbsp;&nbsp;</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.display_name %></td>
        <td><%= member.birth.try :date_string %></td>
        <td><%= member.gender %></td>
        <td><%= member.key %></td>
        <td><%= member.famc_key %></td>
        <td><%= member.fams_keys %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<p>
<%= link_to 'Edit this Record', edit_member_path(@member) %> |
<%= link_to 'Members List', members_path %>
</p>

<strong>Name:</strong>
<%= @member.display_name %>

<br><strong>Gender:</strong>
<%= @member.gender %>

<br><strong>Key:</strong>
<%= @member.key %>

<br><strong>Famc key:</strong>
<%= @member.famc_key %>

<br><strong>Fams keys:</strong>
<%= @member.fams_keys %>

<br><br><strong>Parents:</strong>
<% if @member.parents %>
    <% @member.parents.each do |parent| %>
      <br> >>> <%= link_to parent.display_name, parent %>
    <% end %>
<% end %>

 <br><br><strong>Union(s):</strong>  
  <% @member.families.each do |family| %>
    <br>&nbsp;&nbsp;&nbsp;<%= link_to family.display_name, family %>
    <% family.children.each do |child| %>
    <br>&nbsp;&nbsp;&nbsp; - -> <%= link_to child.display_name, child %>
  <% end %>

  <% end %>

<h4>EVENTS</h4>
<table>
<thead>
  <tr>
    <th>Event&nbsp;&nbsp;&nbsp;</th>
    <th>Date&nbsp;&nbsp;&nbsp;</th>
    <th>Place&nbsp;&nbsp;&nbsp;</th>
  </tr>
</thead>
<tbody>
  <% @member.events.each do |event| %>
    <tr>
      <td><%= event.kind %></td>
      <td><%= event.date_string %></td>
      <td><%= event.place %></td>
     </tr>
  <% end %>
</tbody>
</table>

<h4>Imported Text:</h4>
<% @member.rawtexts.each do |line| %>
    <div><%= line %></div>
<% end %>